# Generated by Django 3.2.5 on 2025-04-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hdr_Image',
        ),
    ]
