# Generated by Django 3.2.5 on 2024-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20240730_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandscomponents_db',
            name='sample',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
    ]
