# Generated by Django 3.2.5 on 2025-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_bandscomponents_db_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresettings_db',
            name='rinsingSolvent',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
