# Generated by Django 3.2.5 on 2025-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_pressuresettings_db_rinsingsolvent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuresettings_db',
            name='nozzlediameter',
            field=models.CharField(default='0.05', max_length=120),
        ),
    ]
