# Generated by Django 3.2.5 on 2025-04-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_alter_pressuresettings_db_nozzlediameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plateproperties_db',
            name='offset_top',
        ),
    ]
