# Generated by Django 3.2.5 on 2025-04-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_auto_20240730_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plateproperties_db',
            name='offset_top',
        ),
    ]
